name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install -y libboost-filesystem-dev libboost-program-options-dev libeigen3-dev libyaml-cpp-dev libassimp-dev libompl-dev liboctomap-dev libfcl-dev
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build
